import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import type { NativeAttributeValue } from '@aws-sdk/lib-dynamodb';
import { BatchGetCommand, DynamoDBDocumentClient, GetCommand, QueryCommand, ScanCommand } from '@aws-sdk/lib-dynamodb';
import type { Schema } from '../../data/resource';

// Backs listPublicGalleries and getPublicGallery, the only way a visitor reads
// the gallery tables. The models are admin-only; this is where admin-only and
// empty galleries are kept out. See docs/adr/0005-public-reads-are-custom-operations.md.

const db = DynamoDBDocumentClient.from(new DynamoDBClient());

const requireEnv = (name: string): string => {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not set`);
  return value;
};

const GALLERY_TABLE = requireEnv('GALLERY_TABLE_NAME');
const IMAGE_TABLE = requireEnv('IMAGE_TABLE_NAME');
const GALLERY_IMAGE_TABLE = requireEnv('GALLERY_IMAGE_TABLE_NAME');

// Generated by Amplify for GalleryImage's `gallery` belongsTo.
const GALLERY_IMAGES_INDEX = 'gsi-Gallery.images';

// BatchGetItem's per-request cap.
const BATCH_GET_MAX = 100;
const BATCH_GET_ATTEMPTS = 5;

type Row = Record<string, NativeAttributeValue>;

interface GalleryRow {
  id: string;
  name: string;
  description?: string | null;
  createdDate: string;
  updatedAt?: string | null;
  thumbnailImageId?: string | null;
  thumbnailCrop?: string | null;
  adminOnly?: boolean | null;
}

interface ImageRow {
  id: string;
  title: string;
  description?: string | null;
  s3Key: string;
  s3ThumbnailKey?: string | null;
  s3DisplayKey?: string | null;
  uploadDate: string;
  contentType?: string | null;
  width?: number | null;
  height?: number | null;
  exifData?: string | null;
}

interface GalleryImageRow {
  id: string;
  galleryId: string;
  imageId: string;
  addedDate: string;
  order?: number | null;
}

type PublicImage = NonNullable<Schema['PublicImage']['type']>;
type PublicGalleryImage = NonNullable<Schema['PublicGalleryImage']['type']>;
type PublicGallery = NonNullable<Schema['PublicGallery']['type']>;

const scanAll = async <T>(tableName: string, projection?: string): Promise<T[]> => {
  const rows: T[] = [];
  let startKey: Row | undefined;
  do {
    const page = await db.send(
      new ScanCommand({ TableName: tableName, ProjectionExpression: projection, ExclusiveStartKey: startKey }),
    );
    rows.push(...((page.Items ?? []) as T[]));
    startKey = page.LastEvaluatedKey;
  } while (startKey);
  return rows;
};

const batchGetImages = async (ids: Iterable<string>): Promise<Map<string, ImageRow>> => {
  const unique = [...new Set(ids)];
  const found = new Map<string, ImageRow>();

  for (let start = 0; start < unique.length; start += BATCH_GET_MAX) {
    let keys: Row[] = unique.slice(start, start + BATCH_GET_MAX).map(id => ({ id }));
    // DynamoDB may return part of a batch as UnprocessedKeys under load; retry
    // those with a short backoff rather than silently dropping photos.
    for (let attempt = 0; keys.length && attempt < BATCH_GET_ATTEMPTS; attempt++) {
      if (attempt > 0) await new Promise(resolve => setTimeout(resolve, 50 * 2 ** attempt));
      const result = await db.send(new BatchGetCommand({ RequestItems: { [IMAGE_TABLE]: { Keys: keys } } }));
      for (const item of (result.Responses?.[IMAGE_TABLE] ?? []) as ImageRow[]) found.set(item.id, item);
      keys = result.UnprocessedKeys?.[IMAGE_TABLE]?.Keys ?? [];
    }
    if (keys.length) throw new Error(`Could not read ${keys.length} images after ${BATCH_GET_ATTEMPTS} attempts`);
  }

  return found;
};

// AWSJSON fields are stored as JSON text. Returned as text, AppSync encodes them
// a second time, so decode first and let AppSync encode once. Unparseable
// values are dropped rather than passed through.
const decodeStoredJson = (value: string | null | undefined): PublicImage['exifData'] => {
  if (!value) return null;
  try {
    return JSON.parse(value) as PublicImage['exifData'];
  } catch {
    return null;
  }
};

// Mapped field by field so the payload can only ever carry these: no file name,
// size or tags, and EXIF only where a page shows it.
const toPublicImage = (row: ImageRow, withExif: boolean): PublicImage => ({
  id: row.id,
  title: row.title,
  description: row.description ?? null,
  s3Key: row.s3Key,
  s3ThumbnailKey: row.s3ThumbnailKey ?? null,
  s3DisplayKey: row.s3DisplayKey ?? null,
  uploadDate: row.uploadDate,
  contentType: row.contentType ?? null,
  width: row.width ?? null,
  height: row.height ?? null,
  exifData: withExif ? decodeStoredJson(row.exifData) : null,
});

const toPublicGallery = (row: GalleryRow, photoCount: number): PublicGallery => ({
  id: row.id,
  name: row.name,
  description: row.description ?? null,
  createdDate: row.createdDate,
  updatedAt: row.updatedAt ?? null,
  thumbnailCrop: decodeStoredJson(row.thumbnailCrop),
  photoCount,
  thumbnailImage: null,
  images: null,
});

const listPublicGalleries = async (): Promise<PublicGallery[]> => {
  const [galleries, memberships] = await Promise.all([
    scanAll<GalleryRow>(GALLERY_TABLE),
    scanAll<Pick<GalleryImageRow, 'galleryId'>>(GALLERY_IMAGE_TABLE, 'galleryId'),
  ]);

  const counts = new Map<string, number>();
  for (const { galleryId } of memberships) counts.set(galleryId, (counts.get(galleryId) ?? 0) + 1);

  // An empty gallery has nothing to show and reads as a broken link.
  const visible = galleries.filter(gallery => gallery.adminOnly !== true && (counts.get(gallery.id) ?? 0) > 0);

  const covers = await batchGetImages(visible.flatMap(gallery => gallery.thumbnailImageId ?? []));

  return visible.map(gallery => {
    const cover = gallery.thumbnailImageId ? covers.get(gallery.thumbnailImageId) : undefined;
    return {
      ...toPublicGallery(gallery, counts.get(gallery.id) ?? 0),
      thumbnailImage: cover ? toPublicImage(cover, false) : null,
    };
  });
};

const compareDisplayOrder = (a: GalleryImageRow, b: GalleryImageRow): number => {
  const aOrder = a.order ?? null;
  const bOrder = b.order ?? null;
  if (aOrder === null && bOrder === null) return a.addedDate.localeCompare(b.addedDate);
  if (aOrder === null) return 1;
  if (bOrder === null) return -1;
  if (aOrder !== bOrder) return aOrder - bOrder;
  return a.addedDate.localeCompare(b.addedDate);
};

const getPublicGallery = async (id: string): Promise<PublicGallery | null> => {
  const { Item } = await db.send(new GetCommand({ TableName: GALLERY_TABLE, Key: { id } }));
  const gallery = Item as GalleryRow | undefined;
  // An admin-only gallery reads exactly like one that does not exist.
  if (!gallery || gallery.adminOnly === true) return null;

  const memberships: GalleryImageRow[] = [];
  let startKey: Row | undefined;
  do {
    const page = await db.send(
      new QueryCommand({
        TableName: GALLERY_IMAGE_TABLE,
        IndexName: GALLERY_IMAGES_INDEX,
        KeyConditionExpression: 'galleryId = :galleryId',
        ExpressionAttributeValues: { ':galleryId': id },
        ExclusiveStartKey: startKey,
      }),
    );
    memberships.push(...((page.Items ?? []) as GalleryImageRow[]));
    startKey = page.LastEvaluatedKey;
  } while (startKey);

  const images = await batchGetImages(memberships.map(membership => membership.imageId));

  const photos: PublicGalleryImage[] = [];
  for (const membership of memberships.sort(compareDisplayOrder)) {
    const image = images.get(membership.imageId);
    // A membership can outlive its image; the editor skips those too.
    if (!image) continue;
    photos.push({
      id: membership.id,
      galleryId: membership.galleryId,
      imageId: membership.imageId,
      addedDate: membership.addedDate,
      order: membership.order ?? null,
      image: toPublicImage(image, true),
    });
  }

  return { ...toPublicGallery(gallery, photos.length), images: photos };
};

type ListEvent = Parameters<Schema['listPublicGalleries']['functionHandler']>[0];
type GetEvent = Parameters<Schema['getPublicGallery']['functionHandler']>[0];

// Dispatched on the arguments, not the field name: Amplify's function resolver
// does not send `info`, although the generated event type declares it. Only
// getPublicGallery takes an id.
export const handler = async (event: ListEvent | GetEvent): Promise<PublicGallery[] | PublicGallery | null> => {
  const id = (event.arguments as Partial<GetEvent['arguments']> | undefined)?.id;
  return id ? getPublicGallery(id) : listPublicGalleries();
};
