/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandboxIndexRouteImport } from './routes/sandbox/index'
import { Route as PhotosIndexRouteImport } from './routes/photos/index'
import { Route as GridDemoIndexRouteImport } from './routes/grid-demo/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as PhotosGalleryIdIndexRouteImport } from './routes/photos/$galleryId/index'
import { Route as BlogNewIndexRouteImport } from './routes/blog/new/index'
import { Route as BlogPostIdIndexRouteImport } from './routes/blog/$postId/index'
import { Route as AdminCameraIndexRouteImport } from './routes/admin/camera/index'
import { Route as PhotosGalleryIdEditRouteImport } from './routes/photos/$galleryId/edit'
import { Route as BlogPostIdEditRouteImport } from './routes/blog/$postId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxIndexRoute = SandboxIndexRouteImport.update({
  id: '/sandbox/',
  path: '/sandbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridDemoIndexRoute = GridDemoIndexRouteImport.update({
  id: '/grid-demo/',
  path: '/grid-demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosGalleryIdIndexRoute = PhotosGalleryIdIndexRouteImport.update({
  id: '/photos/$galleryId/',
  path: '/photos/$galleryId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNewIndexRoute = BlogNewIndexRouteImport.update({
  id: '/blog/new/',
  path: '/blog/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdIndexRoute = BlogPostIdIndexRouteImport.update({
  id: '/blog/$postId/',
  path: '/blog/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCameraIndexRoute = AdminCameraIndexRouteImport.update({
  id: '/admin/camera/',
  path: '/admin/camera/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosGalleryIdEditRoute = PhotosGalleryIdEditRouteImport.update({
  id: '/photos/$galleryId/edit',
  path: '/photos/$galleryId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdEditRoute = BlogPostIdEditRouteImport.update({
  id: '/blog/$postId/edit',
  path: '/blog/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/grid-demo': typeof GridDemoIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/sandbox': typeof SandboxIndexRoute
  '/blog/$postId/edit': typeof BlogPostIdEditRoute
  '/photos/$galleryId/edit': typeof PhotosGalleryIdEditRoute
  '/admin/camera': typeof AdminCameraIndexRoute
  '/blog/$postId': typeof BlogPostIdIndexRoute
  '/blog/new': typeof BlogNewIndexRoute
  '/photos/$galleryId': typeof PhotosGalleryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/grid-demo': typeof GridDemoIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/sandbox': typeof SandboxIndexRoute
  '/blog/$postId/edit': typeof BlogPostIdEditRoute
  '/photos/$galleryId/edit': typeof PhotosGalleryIdEditRoute
  '/admin/camera': typeof AdminCameraIndexRoute
  '/blog/$postId': typeof BlogPostIdIndexRoute
  '/blog/new': typeof BlogNewIndexRoute
  '/photos/$galleryId': typeof PhotosGalleryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/grid-demo/': typeof GridDemoIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/sandbox/': typeof SandboxIndexRoute
  '/blog/$postId/edit': typeof BlogPostIdEditRoute
  '/photos/$galleryId/edit': typeof PhotosGalleryIdEditRoute
  '/admin/camera/': typeof AdminCameraIndexRoute
  '/blog/$postId/': typeof BlogPostIdIndexRoute
  '/blog/new/': typeof BlogNewIndexRoute
  '/photos/$galleryId/': typeof PhotosGalleryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/grid-demo'
    | '/photos'
    | '/sandbox'
    | '/blog/$postId/edit'
    | '/photos/$galleryId/edit'
    | '/admin/camera'
    | '/blog/$postId'
    | '/blog/new'
    | '/photos/$galleryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/grid-demo'
    | '/photos'
    | '/sandbox'
    | '/blog/$postId/edit'
    | '/photos/$galleryId/edit'
    | '/admin/camera'
    | '/blog/$postId'
    | '/blog/new'
    | '/photos/$galleryId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/contact/'
    | '/grid-demo/'
    | '/photos/'
    | '/sandbox/'
    | '/blog/$postId/edit'
    | '/photos/$galleryId/edit'
    | '/admin/camera/'
    | '/blog/$postId/'
    | '/blog/new/'
    | '/photos/$galleryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  GridDemoIndexRoute: typeof GridDemoIndexRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  SandboxIndexRoute: typeof SandboxIndexRoute
  BlogPostIdEditRoute: typeof BlogPostIdEditRoute
  PhotosGalleryIdEditRoute: typeof PhotosGalleryIdEditRoute
  AdminCameraIndexRoute: typeof AdminCameraIndexRoute
  BlogPostIdIndexRoute: typeof BlogPostIdIndexRoute
  BlogNewIndexRoute: typeof BlogNewIndexRoute
  PhotosGalleryIdIndexRoute: typeof PhotosGalleryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/': {
      id: '/sandbox/'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-demo/': {
      id: '/grid-demo/'
      path: '/grid-demo'
      fullPath: '/grid-demo'
      preLoaderRoute: typeof GridDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$galleryId/': {
      id: '/photos/$galleryId/'
      path: '/photos/$galleryId'
      fullPath: '/photos/$galleryId'
      preLoaderRoute: typeof PhotosGalleryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/new/': {
      id: '/blog/new/'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof BlogNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId/': {
      id: '/blog/$postId/'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/camera/': {
      id: '/admin/camera/'
      path: '/admin/camera'
      fullPath: '/admin/camera'
      preLoaderRoute: typeof AdminCameraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$galleryId/edit': {
      id: '/photos/$galleryId/edit'
      path: '/photos/$galleryId/edit'
      fullPath: '/photos/$galleryId/edit'
      preLoaderRoute: typeof PhotosGalleryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId/edit': {
      id: '/blog/$postId/edit'
      path: '/blog/$postId/edit'
      fullPath: '/blog/$postId/edit'
      preLoaderRoute: typeof BlogPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  GridDemoIndexRoute: GridDemoIndexRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  SandboxIndexRoute: SandboxIndexRoute,
  BlogPostIdEditRoute: BlogPostIdEditRoute,
  PhotosGalleryIdEditRoute: PhotosGalleryIdEditRoute,
  AdminCameraIndexRoute: AdminCameraIndexRoute,
  BlogPostIdIndexRoute: BlogPostIdIndexRoute,
  BlogNewIndexRoute: BlogNewIndexRoute,
  PhotosGalleryIdIndexRoute: PhotosGalleryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
