/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotosIndexRouteImport } from './routes/photos/index'
import { Route as GridDemoIndexRouteImport } from './routes/grid-demo/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PhotosGalleryIdIndexRouteImport } from './routes/photos/$galleryId/index'
import { Route as PhotosGalleryIdEditRouteImport } from './routes/photos/$galleryId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridDemoIndexRoute = GridDemoIndexRouteImport.update({
  id: '/grid-demo/',
  path: '/grid-demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosGalleryIdIndexRoute = PhotosGalleryIdIndexRouteImport.update({
  id: '/photos/$galleryId/',
  path: '/photos/$galleryId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosGalleryIdEditRoute = PhotosGalleryIdEditRouteImport.update({
  id: '/photos/$galleryId/edit',
  path: '/photos/$galleryId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/grid-demo': typeof GridDemoIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/photos/$galleryId/edit': typeof PhotosGalleryIdEditRoute
  '/photos/$galleryId': typeof PhotosGalleryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/grid-demo': typeof GridDemoIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/photos/$galleryId/edit': typeof PhotosGalleryIdEditRoute
  '/photos/$galleryId': typeof PhotosGalleryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/grid-demo/': typeof GridDemoIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/photos/$galleryId/edit': typeof PhotosGalleryIdEditRoute
  '/photos/$galleryId/': typeof PhotosGalleryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/grid-demo'
    | '/photos'
    | '/photos/$galleryId/edit'
    | '/photos/$galleryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/grid-demo'
    | '/photos'
    | '/photos/$galleryId/edit'
    | '/photos/$galleryId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/'
    | '/grid-demo/'
    | '/photos/'
    | '/photos/$galleryId/edit'
    | '/photos/$galleryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  GridDemoIndexRoute: typeof GridDemoIndexRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  PhotosGalleryIdEditRoute: typeof PhotosGalleryIdEditRoute
  PhotosGalleryIdIndexRoute: typeof PhotosGalleryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-demo/': {
      id: '/grid-demo/'
      path: '/grid-demo'
      fullPath: '/grid-demo'
      preLoaderRoute: typeof GridDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$galleryId/': {
      id: '/photos/$galleryId/'
      path: '/photos/$galleryId'
      fullPath: '/photos/$galleryId'
      preLoaderRoute: typeof PhotosGalleryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$galleryId/edit': {
      id: '/photos/$galleryId/edit'
      path: '/photos/$galleryId/edit'
      fullPath: '/photos/$galleryId/edit'
      preLoaderRoute: typeof PhotosGalleryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  GridDemoIndexRoute: GridDemoIndexRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  PhotosGalleryIdEditRoute: PhotosGalleryIdEditRoute,
  PhotosGalleryIdIndexRoute: PhotosGalleryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
